name: Update rss feed

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  reglugerdir.rss:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - name: Create reglugerdir.rss file
      run: python reglugerdir.py
    - name: Commit changes
      run: |
        git add .
        git config --global user.email "rssbot@example.com"
        git config --global user.name "RSS þjarkur"
        git commit --allow-empty -m 'uppfærsla'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
