name: Update rss feed

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 8-17 * * *"
jobs:
  make_rss_feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r requirements.txt
      #- name: Get installed Playwright version
      #  id: playwright-version
      #  run: echo "PLAYWRIGHT_VERSION=$(playwright --version)" >> $GITHUB_ENV
      #- name: Cache playwright binaries
      #  uses: actions/cache@v4
      #  id: playwright-cache
      #  with:
      #    path: |
      #      ~/.cache/ms-playwright
      #    key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      #- run: python -m playwright install
      #  if: steps.playwright-cache.outputs.cache-hit != 'true'
      # - name: Create reglugerdir.rss file
      #   run: python src/reglugerdir.py
      # - name: Create skjalaskrar.rss file
      #   run: python src/skjalaskrar.py
      - name: Create palmemordsarkivet.rss file
        run: python src/palmemordsaarkivet.py
        if: always()
      - name: Create ritgerdir.rss file
        run: python src/ritgerdir.py
        if: always()
      # - name: Create skipulag_rvk.rss file
      #   run: python src/skipulag_rvk.py
      # - name: Create landskjorstjorn.rss file
      #   run: python src/landskjorstjorn.py
      - name: create island_is feeds
        run: python src/island-is.py
        if: always()
      - name: create readme
        run: python src/create_readme.py
        if: always()
      - name: Commit changes
        if: always()
        run: |
          git add .
          git config --global user.email "rssbot@example.com"
          git config --global user.name "RSS þjarkur"
          git commit --allow-empty -m 'uppfærsla'
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
